# Generated by Django 5.2.8 on 2025-11-27 08:08

import django.db.models.deletion
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=500, upload_to=documents.models.document_upload_path
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="File size in bytes"),
                ),
                (
                    "file_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA256 hash of file contents",
                        max_length=64,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["-uploaded_at"], name="documents_d_uploade_78ffff_idx"
                    ),
                    models.Index(
                        fields=["file_hash"], name="documents_d_file_ha_a7f76e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ParsedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[("docx", "DOCX"), ("pdf", "PDF")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("parsed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "metadata_json",
                    models.JSONField(default=dict, help_text="Document metadata"),
                ),
                (
                    "sections_json",
                    models.JSONField(
                        default=list, help_text="Parsed sections hierarchy"
                    ),
                ),
                (
                    "text_json",
                    models.JSONField(default=dict, help_text="Extracted text content"),
                ),
                (
                    "tables_json",
                    models.JSONField(default=list, help_text="Extracted tables"),
                ),
                (
                    "images_json",
                    models.JSONField(
                        default=list, help_text="Extracted images metadata"
                    ),
                ),
                (
                    "extras_json",
                    models.JSONField(
                        default=dict, help_text="Additional parsing information"
                    ),
                ),
                ("page_count", models.PositiveIntegerField(blank=True, null=True)),
                ("table_count", models.PositiveIntegerField(default=0)),
                ("image_count", models.PositiveIntegerField(default=0)),
                ("section_count", models.PositiveIntegerField(default=0)),
                (
                    "has_ocr",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="OCR was applied during parsing",
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "document",
                    models.OneToOneField(
                        help_text="The uploaded document file",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parsed_data",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "ordering": ["-parsed_at"],
                "indexes": [
                    models.Index(
                        fields=["-parsed_at"], name="documents_p_parsed__e7c845_idx"
                    ),
                    models.Index(
                        fields=["source_type"], name="documents_p_source__e124e3_idx"
                    ),
                    models.Index(
                        fields=["author"], name="documents_p_author_937688_idx"
                    ),
                    models.Index(
                        fields=["has_ocr"], name="documents_p_has_ocr_55c7e9_idx"
                    ),
                ],
            },
        ),
    ]
